services:
  - type: worker
    name: telegram-sorter-bot
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
